### ISSUE TITLE
大大，dbm的皮肤美化代码是不是有问题呀。

### ISSUE THREAD

**Issue by schokoTT** [ViolyS/RayUI_VS#4]
玩的时候感觉dbm皮肤会错位，无论是不是在rayui设置中更改dbm皮肤美化还是存在问题。
我应该关掉rayui，单独试试dbm的，但是好像忘记了。

**Comment by tikkt** [comment]
RayUI\modules\skins\addons\dbm.lua里修改difv的值？

**Comment by schokoTT** [comment]
我想直接把这个文件删了，因为老是有两种皮肤同时存在，可难看了。而且细条版的不怎么好点 ，除了好看

**Comment by ViolyS** [comment]
改difv为0就是原版了
